name: Publish npm Package

on:
  release:
    types: [released]

jobs:
  publish:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - uses: actions/setup-node@v1
          with:
            node-version: 12
        - run: npm install
        - run: npm test filter-and-highlight
        - uses: JS-DevTools/npm-publish@v1
          with:
            token: ${{ secrets.NPM_TOKEN }}
            package: ./dist/filter-and-highlight/package.json
            access: public